AllCops:
  TargetRubyVersion: 2.7.1
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "db/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "config/**/*"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 20
